### PR TITLE
Upgrade eslint config simplifield plugin

### PR DESCRIPTION
**Pull request by SebastienElet**

### CODE REVIEW

**Comment by pedrorijo91** [comment]
Hey @SebastienElet,

Thanks for the contribution! Unfortunately some tests are failing on circleci. Can you have a look please? :)

Thanks,
Pedro

**Comment by rtfpessoa** [comment]
Fixed in #53

**Comment by SebastienElet** [comment]
Thanks a lot, sorry but i missed your message :/

**Comment by rtfpessoa** [comment]
Np. It was not your fault. Apparently some tests were not correct "syntactically" and ESLint parser started detecting it now.

**Pull request closed without merging**
