### PR TITLE
Add eslint config simplifield plugin

### PR DESCRIPTION
**Pull request by SebastienElet**

### CODE REVIEW

**Comment by rtfpessoa** [comment]
@SebastienElet can you rebase with master. We had to fix a weird problem with sbt.

**Comment by SebastienElet** [comment]
@rtfpessoa thanks for the feedback, rebase is done (🙏  for the build)

**Comment by SebastienElet** [comment]
There an issue with https://github.com/codacy/codacy-eslint/blob/master/src/main/resources/docs/tests/no-multiple-empty-lines.js

I think this come from the refactoring of this rule in eslint 3.8 (https://github.com/eslint/eslint/commit/3b11d3f1b39801019acd236639a656f8db07c251)

I don't know where is the truth :/

**Comment by rtfpessoa** [comment]
What you need, is to change `//#Issue: {"severity": "Info", "line": 6, "patternId": "no-multiple-empty-lines"}` to  `//#Issue: {"severity": "Info", "line": 4, "patternId": "no-multiple-empty-lines"}`

And it should be fine after.

**Comment by SebastienElet** [comment]
Done

**Comment by rtfpessoa** [comment]
LGTM :+1:

**Pull request merged**
