### PR TITLE
Added missing docs for security_detect-object-injection

### PR DESCRIPTION
**Pull request by tompahoward**

### CODE REVIEW

**Comment by tompahoward** [comment]
Looks like use-isnan.js is borken, but I can't see how it's related to my pull. 🤔

**Comment by rtfpessoa** [comment]
This definitely should not be your fault. I will take a look.

**Comment by rtfpessoa** [comment]
Please rebase with master. Tests fixed in #53.

**Comment by rtfpessoa** [comment]
Picked in f99122fc238bf851a8e8dd8e9aa3838de8bf0c34

**Pull request closed without merging**
