### PR TITLE
feature/minor-eslint-plugin-updates

### PR DESCRIPTION
**Pull request by LaurensBosscher**
Minor deps updates to the latest version. Shouldn't contain any breaking changes, should fix a bunch of ```Definition for rule '...' was not found ``` issues.

### CODE REVIEW

**Comment by LaurensBosscher** [comment]
There are 6 commits on this PR because it was submitted initially without merging the remote master. Fixing that took a few tries :) Just to be sure I double checked everything manually, versions numbers should be fine now.

**Comment by FloEdelmann** [comment]
@LaurensBosscher Would you mind updating `eslint-plugin-vue` to version `5.2.1` as well? See https://github.com/vuejs/eslint-plugin-vue/releases. Otherwise I'll open another PR :)

**Comment by LaurensBosscher** [comment]
@FloEdelmann,

Sure! See latest commit :)

**Comment by FloEdelmann** [comment]
@rtfpessoa Any update when this can be merged? I'm getting lots of "Definition for rule ... was not found" errors lately: https://app.codacy.com/app/open-fixture-library/open-fixture-library/issues

**Comment by LaurensBosscher** [comment]
@FloEdelmann 

schermafbeelding 2019-03-05 om 11 08 33

We're in the process of migrating away from Codacy to Github Actions because an outdated linter is not very useful for us.

Quite a shame, it would literally take 5 minutes to approve this PR and I'm sure we're not the only company that has this issue.

**Comment by FloEdelmann** [comment]
@bmbferreira @machadoit @rtfpessoa Still no plans to review and merge this PR? It just updates some already existing dependencies, so nothing new to maintain, just fixes for all those "Definition for rule ... was not found" errors many people using Codacy are getting. Despite that, it's already open (and ignored) for two months!

**Comment by busheezy** [comment]
Why is this being ignored?

**Comment by LaurensBosscher** [comment]
> Why is this being ignored?

cc: @bmbferreira @machadoit @rtfpessoa

They have different priorities. We've cancelled our subscription, we're very unhappy with the way this issue is being handled. Expecting your customers to take care of your updates is already quite lazy, ignoring PR's (of paying customers) for months is just horrible.

I've received a few e-mails that they would add it to their sprint but no action has been undertaken.

You're better of running eslint as part of your CI process or look at a Codacy alternative.

**Comment by FloEdelmann** [comment]
@gjsduarte, @DReigada As you've approved and merged #130 today, could you maybe have a look at this PR as well?

**Comment by gjsduarte** [comment]
@FloEdelmann 
Thanks for reaching out! Yes, we will be taking a look at this PR within the next week. 
Unfortunately we can't directly merge it, because it's missing documentation updates. Exactly the same as you can see the PR #130.
This constraint and some reviewing bandwidth limitations from our side caused this to drag longer than desired.
Anyway, our plan is to take over your PR and add the missing documentation in order to have it ready for merging.

**Comment by busheezy** [comment]
Can we make sure the modules are still up to date so we aren't using this opportunity to merge old modules?

Thanks

**Comment by gjsduarte** [comment]
Sure thing @busheezy. I'll make sure we do so.

**Comment by busheezy** [comment]
Thank you, @gjsduarte. Have a good day, everyone.

**Comment by peavers** [comment]
Hi @LaurensBosscher thanks for taking the time to submit this pull request. It has been merged into a bigger request (#133) which has the latest modules updated.

**Pull request closed without merging**
